In [27]:
import pandas as pd
import numpy as np

# Series


In [2]:
data = pd.Series([0.25,0.5,0.75,1.0])

In [3]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data = pd.Series([0.25,0.5,0.75,1.0], index = ['a','b','c','d'])

In [5]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data = pd.Series(['a','b','c','d'])
data

0    a
1    b
2    c
3    d
dtype: object

In [10]:
data = pd.Series([1,2,3,4])

In [11]:
data


0    1
1    2
2    3
3    4
dtype: int64

In [12]:
data.values

array([1, 2, 3, 4])

In [13]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [23]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [24]:
population = pd.Series(population_dict)

In [25]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [26]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [28]:
a = np.linspace(0,10,6)

In [29]:
print(a)
a[0:3]


[ 0.  2.  4.  6.  8. 10.]


array([0., 2., 4.])

In [33]:
series = [
    pd.Series([1, 2, 3]),
    pd.Series(5, index=[1, 2, 3]),
    pd.Series({'a': 1, 'b': 2, 'c': 42}),
    pd.Series(np.arange(2,20,3))
]

for serie in series:
    print(serie)

0    1
1    2
2    3
dtype: int64
1    5
2    5
3    5
dtype: int64
a     1
b     2
c    42
dtype: int64
0     2
1     5
2     8
3    11
4    14
5    17
dtype: int64


# DataFrame


In [34]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [35]:
area = pd.Series(area_dict)

In [36]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [122]:
states = pd.DataFrame({'population': population,
                      'area': area})

In [38]:
states


population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [40]:
states.loc['Florida']['population']

19552860

In [41]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [42]:
states.columns

Index(['population', 'area'], dtype='object')

# DataFrame Tworzenie

In [47]:
data = [{'a':i,'b': 2 * i}
       for i in range(5)]
dfs = [
    pd.DataFrame(population, columns=['population']),
    pd.DataFrame(data),
    pd.DataFrame([{'a':1,'b':2},
                 {'b':3,'c':4}]),
    pd.DataFrame(np.random.rand(3, 2),
                columns=['foo', 'bar'],
                index=['a', 'b', 'c'])
    
]

In [48]:
for df in dfs:
    print('-'*10)
    print(df)

----------
            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
----------
   a  b
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8
----------
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0
----------
        foo       bar
a  0.251728  0.295142
b  0.693999  0.204190
c  0.994952  0.398814


In [57]:
c = pd.DataFrame(np.random.rand(3, 2),
                columns=['foo', 'bar'],
                index=['a', 'b', 'c'])

In [58]:
c.loc['b']

foo    0.180340
bar    0.102725
Name: b, dtype: float64

## INDEKSOWANIE i WYBIERANIE DANYCH PANDAS


In [60]:
ind = pd.Index([2, 3, 5, 7, 11]) # Indeksy są nie mutowalne, nie da się ich zmieniać.
ind[1] = 0

TypeError: Index does not support mutable operations

In [61]:
data = pd.Series(['a','b','c'], index = [1,3,5])

In [62]:
data[1]

'a'

In [63]:
data[1:3] # tu działa jak tablica jeśli robimy slice na liczbach !!

3    b
5    c
dtype: object

In [64]:
# loc <- indeks z typu Series
data.loc[1]

'a'

In [65]:
data.loc[1:3] # działa na nazwach Indeksów

1    a
3    b
dtype: object

In [66]:
data.iloc[1:3] # działa jak na tablicy a nie na nazwach indeksów

3    b
5    c
dtype: object

In [67]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [124]:
states['density'] = states['population']/states['area']

In [125]:
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [71]:
states.iloc[:3, :2] # pierszy indeks do 3 a drugi do 2giego

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [72]:
# 2 wymiary!!! DataFrame
states.loc[:'Texas', :'population']

population
California    38332521
Texas         26448193

In [73]:
# 1 wymiar!! Series
states['population'].loc[:'Texas']

California    38332521
Texas         26448193
Name: population, dtype: int64

In [74]:
states.density > 100

California    False
Texas         False
New York       True
Florida        True
Illinois      False
Name: density, dtype: bool

In [75]:
states['density'] > 100

California    False
Texas         False
New York       True
Florida        True
Illinois      False
Name: density, dtype: bool

In [78]:
pd.unique(states.index)

array(['California', 'Texas', 'New York', 'Florida', 'Illinois'],
      dtype=object)

In [80]:
# Tworzenie i usuwanie kolumny

states['2density'] = 2 * states['density']

states

population    area     density    2density
California    38332521  423967   90.413926  180.827852
Texas         26448193  695662   38.018740   76.037481
New York      19651127  141297  139.076746  278.153492
Florida       19552860  170312  114.806121  229.612241
Illinois      12882135  149995   85.883763  171.767526

In [81]:
del states['2density']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [82]:
states.loc[states['density']>100]

population    area     density
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121

In [87]:
states.loc[pd.unique(states.index)]

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [89]:
states.iloc[0,2] = 90 # wiersz 0 kolumna 2 licząc od 0 ra
states

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

### OPEROWANIE NA BRAKUJĄCYCH DANYCH W PANDAS

In [90]:

vals1 = np.array([1, None, 3, 4])

In [91]:
vals1

array([1, None, 3, 4], dtype=object)

In [92]:
object

object

In [93]:
a = 1

In [94]:
a is object

False

In [95]:
isinstance(1, object)

True

In [96]:
for dtype in ['object','int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum() # tutaj mamy numpy który liczy sumę z miliona liczb dla typu albo object albo in

dtype = object
62.1 ms ± 2.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
dtype = int
1.18 ms ± 8.37 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [97]:
vals1.sum() # bo jest jeden None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [99]:
type(np.nan) # wartość liczbowa która nie istnieje

float

In [100]:
type(None)

NoneType

In [104]:
vals2 = np.array([1,np.nan,3, 4])

In [105]:
vals2.dtype

dtype('float64')

In [106]:
vals2.sum() # tutaj znajdzie jeden nan i da nan

nan

In [107]:
np.nansum(vals2) # omija npnan i liczy sumę

8.0

In [109]:
print(np.nanmin(vals2))
np.nanmax(vals2)

1.0


4.0

# A W PANADAS JEST INACZEJ

In [110]:
data = pd.Series([1,np.nan, 2.0, None]) # ładnie zamienia
data

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [111]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [113]:
data.loc[data.isnull()]

1   NaN
3   NaN
dtype: float64

In [114]:
data.loc[data.notnull()]

0    1.0
2    2.0
dtype: float64

In [120]:
states.loc['Florida']

population    1.955286e+07
area          1.703120e+05
density       1.148061e+02
Florida                NaN
Name: Florida, dtype: float64

In [127]:
states.loc['Florida', 'population'] = None
states.loc['California', 'population'] = None
states.loc['California', 'area'] = None
states.loc['California', 'density'] = None
for axis in (0, 1):
    for how in ('any', 'all'):
        print(f'axis={axis}, how={how}')
        print(states.dropna(axis=axis, how=how))
        print('-'*10)

axis=0, how=any
          population      area     density
Texas     26448193.0  695662.0   38.018740
New York  19651127.0  141297.0  139.076746
Illinois  12882135.0  149995.0   85.883763
----------
axis=0, how=all
          population      area     density
Texas     26448193.0  695662.0   38.018740
New York  19651127.0  141297.0  139.076746
Florida          NaN  170312.0  114.806121
Illinois  12882135.0  149995.0   85.883763
----------
axis=1, how=any
Empty DataFrame
Columns: []
Index: [California, Texas, New York, Florida, Illinois]
----------
axis=1, how=all
            population      area     density
California         NaN       NaN         NaN
Texas       26448193.0  695662.0   38.018740
New York    19651127.0  141297.0  139.076746
Florida            NaN  170312.0  114.806121
Illinois    12882135.0  149995.0   85.883763
----------


In [128]:
states
states

population      area     density
California         NaN       NaN         NaN
Texas       26448193.0  695662.0   38.018740
New York    19651127.0  141297.0  139.076746
Florida            NaN  170312.0  114.806121
Illinois    12882135.0  149995.0   85.883763

In [131]:
n = np.arange(10,20)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [132]:
index2d = np.array([[3,5],[4,6]])
index2d

array([[3, 5],
       [4, 6]])

In [133]:
n[index2d]

array([[13, 15],
       [14, 16]])

In [135]:
new_data = states[['population','area']] # nowy DF z innego, ważne jest to że muszą być dwa kwadratowe bo tak to by szukał kolumny o nazwie 'population','area'

In [136]:
new_data

population      area
California         NaN       NaN
Texas       26448193.0  695662.0
New York    19651127.0  141297.0
Florida            NaN  170312.0
Illinois    12882135.0  149995.0

In [137]:
states

population      area     density
California         NaN       NaN         NaN
Texas       26448193.0  695662.0   38.018740
New York    19651127.0  141297.0  139.076746
Florida            NaN  170312.0  114.806121
Illinois    12882135.0  149995.0   85.883763

In [142]:
## łącznie obiektów pandas
ser1 = pd.Series(['a','b','c'],index=[1,2,3])
ser2 = pd.Series(['d','e','f'], index=[4,5,6])

pd.concat([ser1,ser2]).reset_index(drop=True) # wtedy powstanie nowy indeks w przeciwnym wypadku dopisze kolejną kolumnę z nowym indeksem

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [148]:
def make_df(cols,ind):
    data ={
        c:[str(c)+str(i)for i in ind] for c in cols
    }
    print(data)
    return pd.DataFrame(data,ind)

In [151]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
df3 = make_df('AB',[1,4])


{'A': ['A1', 'A2'], 'B': ['B1', 'B2']}
{'A': ['A3', 'A4'], 'B': ['B3', 'B4']}
{'A': ['A1', 'A4'], 'B': ['B1', 'B4']}


In [147]:
for axis in (0, 1):
    print(f'axis={axis}')
    print(pd.concat([df1, df2], axis=axis))
    print('-'*10)

axis=0
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
----------
axis=1
     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4
----------


In [152]:
for axis in (0, 1):
    print(f'axis={axis}')
    print(pd.concat([df1, df2, df3], axis=axis))
    print('-'*10)

axis=0
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
1  A1  B1
4  A4  B4
----------
axis=1
     A    B    A    B    A    B
1   A1   B1  NaN  NaN   A1   B1
2   A2   B2  NaN  NaN  NaN  NaN
3  NaN  NaN   A3   B3  NaN  NaN
4  NaN  NaN   A4   B4   A4   B4
----------


In [153]:
df1.append(df2)

/var/folders/8j/f455zbs16591fs29cwfjvqhh0000gn/T/ipykernel_20862/3062608662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

# JOIN :D 



In [154]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [155]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [156]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [163]:
pd.merge(df1,df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [166]:
df22 = df2.rename(columns = {'employee':'employe'}) # zmiana nazwy kolumny :D

In [168]:
pd.merge(df1,df22, left_on='employee', right_on='employe')

employee        group employe  hire_date
0      Bob   Accounting     Bob       2008
1     Jake  Engineering    Jake       2012
2     Lisa  Engineering    Lisa       2004
3      Sue           HR     Sue       2014

In [169]:
df3 = pd.merge(df1,df2)

In [170]:
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [173]:
df3.loc[0, 'hire_date'] = 2007
pd.merge(df2, df3, on='employee')

employee  hire_date_x        group  hire_date_y
0     Lisa         2004  Engineering         2004
1      Bob         2008   Accounting         2007
2     Jake         2012  Engineering         2012
3      Sue         2014           HR         2014

In [193]:
df3.loc[0]['hire_date']

2007

In [187]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

In [194]:
df1 = make_df('AB',[1,2,4])
df2 = make_df('ABCD',[1,2,5,6])

{'A': ['A1', 'A2', 'A4'], 'B': ['B1', 'B2', 'B4']}
{'A': ['A1', 'A2', 'A5', 'A6'], 'B': ['B1', 'B2', 'B5', 'B6'], 'C': ['C1', 'C2', 'C5', 'C6'], 'D': ['D1', 'D2', 'D5', 'D6']}


Joiny w rózny sposób


In [198]:

print(df1)
print ('---'*10)
print(df2)
print ('---'*10)
for how in ('left','right','outer','inner'):
    print (f'df1 {how} join df2')
    print (pd.merge(df1,df2, how = how, on = 'A'))
    print ('---'*10)

    A   B
1  A1  B1
2  A2  B2
4  A4  B4
------------------------------
    A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
5  A5  B5  C5  D5
6  A6  B6  C6  D6
------------------------------
df1 left join df2
    A B_x  B_y    C    D
0  A1  B1   B1   C1   D1
1  A2  B2   B2   C2   D2
2  A4  B4  NaN  NaN  NaN
------------------------------
df1 right join df2
    A  B_x B_y   C   D
0  A1   B1  B1  C1  D1
1  A2   B2  B2  C2  D2
2  A5  NaN  B5  C5  D5
3  A6  NaN  B6  C6  D6
------------------------------
df1 outer join df2
    A  B_x  B_y    C    D
0  A1   B1   B1   C1   D1
1  A2   B2   B2   C2   D2
2  A4   B4  NaN  NaN  NaN
3  A5  NaN   B5   C5   D5
4  A6  NaN   B6   C6   D6
------------------------------
df1 inner join df2
    A B_x B_y   C   D
0  A1  B1  B1  C1  D1
1  A2  B2  B2  C2  D2
------------------------------


In [199]:
df1.merge(df2)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2

# Agregacja i Grupowanie

In [200]:
df = pd.DataFrame({
    'A': np.random.rand(5),
    'B': np.random.rand(5)
})
df

A         B
0  0.343560  0.211852
1  0.892998  0.588524
2  0.699193  0.350266
3  0.410420  0.349114
4  0.810807  0.209190

In [201]:
df.mean()

A    0.631395
B    0.341789
dtype: float64

In [202]:
df.count()

A    5
B    5
dtype: int64

In [203]:
df.min()

A    0.34356
B    0.20919
dtype: float64

In [204]:
df.max()

A    0.892998
B    0.588524
dtype: float64

In [213]:
print(df.mean())
print(df.count())  # zlicz niepuste wartości
print(df.median())
print(df.min())
print(df.max())
print(df.std())
print(df.var())
print(df.prod())
print(df.sum())

data    2.5
dtype: float64
key     6
data    6
dtype: int64
data    2.5
dtype: float64
key     A
data    0
dtype: object
key     C
data    5
dtype: object
data    1.870829
dtype: float64
data    3.5
dtype: float64
data    0
dtype: int64
key     ABCABC
data        15
dtype: object


/var/folders/8j/f455zbs16591fs29cwfjvqhh0000gn/T/ipykernel_20862/1300372130.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.mean())
/var/folders/8j/f455zbs16591fs29cwfjvqhh0000gn/T/ipykernel_20862/1300372130.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.median())
/var/folders/8j/f455zbs16591fs29cwfjvqhh0000gn/T/ipykernel_20862/1300372130.py:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.std())
/var/folders/8j/f455zbs16591fs29cwfjvqhh0000gn/T/ipyke

In [220]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data2': range(5,11),
                   'data': range(6)}, columns=['key','data2','data'])
df

key  data2  data
0   A      5     0
1   B      6     1
2   C      7     2
3   A      8     3
4   B      9     4
5   C     10     5

In [221]:
df.groupby('key').count()

data2  data
key             
A        2     2
B        2     2
C        2     2

In [222]:
df.groupby('key').sum()

data2  data
key             
A       13     3
B       15     5
C       17     7

In [225]:
df.groupby('key')[['data','data2']].sum()

data  data2
key             
A       3     13
B       5     15
C       7     17

In [226]:
df.drop('data2', axis=1).groupby('key').sum()

data
key      
A       3
B       5
C       7

In [231]:
df[df['key']=='A'][['data','data2']].sum()

data      3
data2    13
dtype: int64

In [232]:
df[df['key']=='A'][['data','data2']]

data  data2
0     0      5
3     3      8