In [6]:
import numpy as np
import timeit

In [7]:
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

0.16259778099993127

In [8]:
l =[1,"2", True, 3.0, None]

In [9]:
[type(item) for item in l]

[int, str, bool, float, NoneType]

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
np.array([4.1,2,3,4,5])

array([4.1, 2. , 3. , 4. , 5. ])

In [15]:
s = np.array([1,2,3,4,5,'t'])

In [16]:
[type(item) for item in s]

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

In [17]:
np.array([range(i,i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((5,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
np.random.normal(0,1,(3,3))

array([[-1.15815833, -0.49636909, -0.04707202],
       [-2.71514753,  0.04620521,  1.82140491],
       [-0.76663724, -1.5722221 ,  0.81309383]])

In [25]:
# Tablica o wymiarach 4 na 5 liczby całkowite wylosowane z przedziału [0,10)
np.random.randint(0,10,(4,5))

array([[9, 6, 2, 1, 8],
       [1, 5, 2, 4, 3],
       [3, 9, 0, 5, 7],
       [0, 5, 0, 6, 6]])

https://numpy.org/doc/stable/user/basics.types.html


In [43]:
x = np.random.randint(100, size=(2,3,4))

In [44]:
x

array([[[98, 19, 44, 49],
        [83, 85, 45, 27],
        [38, 80, 70, 53]],

       [[83, 19, 90, 88],
        [99, 51, 81, 96],
        [10, 45, 15,  3]]])

In [45]:
print(f"x ndim: {x.ndim}") #liczba wymiarów
print(f"x ndim: {x.shape}") #wymiar tablicy
print(f"x ndim: {x.size}") #całkowity rozmiar tablicy


x ndim: 3
x ndim: (2, 3, 4)
x ndim: 24


In [47]:
print(f" typ talicy dtype: {x.dtype}")

 typ talicy dtype: int64


In [48]:
print(f"itemsize: {x.itemsize} bytes")  # rozmiar jednego elementu
print(f"nbytes: {x.nbytes} bytes")  # rozmiar całej tablicy (itemsize x size)

itemsize: 8 bytes
nbytes: 192 bytes


In [51]:
y = np.arange(0,10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
y[5]

5

In [56]:
x


array([[[98, 19, 44, 49],
        [83, 85, 45, 27],
        [38, 80, 70, 53]],

       [[83, 19, 90, 88],
        [99, 51, 81, 96],
        [10, 45, 15,  3]]])

In [59]:
x[0][1][0]

83

In [64]:
x[0][1][0:2] = 44 

In [65]:
x

array([[[98, 19, 44, 49],
        [44, 44, 45, 27],
        [38, 80, 70, 53]],

       [[83, 19, 90, 88],
        [99, 51, 81, 96],
        [10, 45, 15,  3]]])

In [63]:
y[:5]

array([0, 1, 2, 3, 4])

In [66]:
y[::-1] # od tyłu tablica

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
x

array([[[98, 19, 44, 49],
        [44, 44, 45, 27],
        [38, 80, 70, 53]],

       [[83, 19, 90, 88],
        [99, 51, 81, 96],
        [10, 45, 15,  3]]])

In [68]:
x[:1,:,:3] # pierwszy podaje która tablica,:1 to jest do 1 ale bez 1, : to wszystkie argumenty z danego wymiaru, :3 od 0 do 3 ale bez 3.

array([[[98, 19, 44],
        [44, 44, 45],
        [38, 80, 70]]])

In [69]:
l1 = [1,2,3]
l2 = l1[2:] # to już generuje nową tablicę, czyli slice robi nową
l2

[3]

In [70]:
l2 = 4

In [71]:
l2

4

In [72]:
l3 = l1 # uwaga takie przypisanie napisze równierz l1 jeśli zmienimy coś w l3 !!!

In [77]:
l3[2]=5

In [78]:
l1

[1, 2, 5]

In [80]:
l3

[1, 2, 5]

In [81]:
x = np.zeros((2,3))

In [82]:
x = np.zeros((2, 3))
y = x[0, :]
y[0] = 1
print(x)  # x i y reprezentują tą samą tablicę!
print(y)  # x i y reprezentują tą samą tablicę!

[[1. 0. 0.]
 [0. 0. 0.]]
[1. 0. 0.]


In [83]:
x_copy = x[:2, :2].copy()
x_copy[0, 0] = 42

print(x)
print(x_copy)  # zmiana x_copy nie zmieniła x

[[1. 0. 0.]
 [0. 0. 0.]]
[[42.  0.]
 [ 0.  0.]]


In [84]:
x

array([[1., 0., 0.],
       [0., 0., 0.]])

In [85]:
y

array([1., 0., 0.])

In [90]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
x = np.array([1, 2, 3])
print(x)
print(x.reshape((1, 3))) # dwuwymiarowa tablica z jednym wierszem i trzema kolumnami
print(x.reshape((3, 1))) # dwuwymiarowa tablica z trzema wierszami i jedną kolumną

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [94]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) #łączenie tablic, należy podać w []

array([1, 2, 3, 3, 2, 1])

In [100]:
grid = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [101]:
print(np.concatenate([grid, grid]))


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
print(np.concatenate([grid, grid], axis=1))  # łączenie wzdłuż drugiego wymiaru 0 lub 1 daje albo poziom albo pion

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [105]:
x = np.array([1,2,3])

In [106]:
grid = np.array([[9,8,7],
                [6,5,4]])

In [109]:
print(np.vstack([x,grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [110]:

y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [118]:
x = np.arange(10)
x1, x2, x3 = np.split(x, [2, 4]) # pierwsza wartość to do jakiej wartości jest end pierszej tablicy, a druga to od czego zaczynamy, przez co powstają 2 plus ewewntualnie jedna z niewybranymi

print(x1, x2, x3)  # zauważ, że dwa punkty dzielenia tworzą trzy tablice

[0 1] [2 3] [4 5 6 7 8 9]


In [119]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i, value in enumerate(values):
        output[i] = 1.0 / value
    return output

In [120]:
values = np.random.randint(1, 10, size=5)

In [121]:
compute_reciprocals(values)

array([0.11111111, 0.14285714, 0.16666667, 0.11111111, 0.2       ])

In [122]:
compute_reciprocals(values)

array([0.11111111, 0.14285714, 0.16666667, 0.11111111, 0.2       ])

In [123]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [124]:
%timeit compute_reciprocals(big_array) # liczy średnią ważne że trzeba dać %- to wywoła kilka razy

2.23 s ± 33.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [125]:
%timeit 1.0 / big_array # wywołane wektorowo znacznie szybciej jak pracujemy wprowst na numpy a nie zwykłym loop

1.42 ms ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [126]:
t = 1.0 / big_array # uwaga big_array jest stworzony przez numpy !!!!

In [127]:
t

array([0.01010101, 0.0106383 , 0.03225806, ..., 0.03225806, 0.08333333,
       0.01149425])

In [134]:
x = np.arange(4)

In [135]:
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


In [139]:
L = np.random.random(100) # size tylko podajemy bo random.randol losuje 1 lub 0. 100 razy shift + tab pokazuje w jupyter co robi funkcja
print(np.sum(L), np.min(L), np.max(L), np.average(L))

51.921853563725385 0.008798190610459278 0.9969575212514493 0.5192185356372538


In [140]:
%timeit np.sum(L)
%timeit sum(L)

3.85 µs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
7.28 µs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [165]:
M = np.random.randint(10, size=(4,3, 4))
print(M)

[[[1 6 6 5]
  [6 3 8 6]
  [5 8 1 5]]

 [[9 6 8 9]
  [4 5 0 6]
  [2 9 0 5]]

 [[7 6 8 1]
  [0 4 0 7]
  [0 0 9 0]]

 [[3 4 4 1]
  [1 7 2 0]
  [1 2 4 3]]]


In [166]:

print(M.sum(axis=2)) # sumy w kolumnach, przejdzie po wierszach ale sumuje w dół, odwrotnie split


[[18 23 19]
 [32 15 16]
 [22 11  9]
 [12 10 10]]


In [167]:
print(M.min(axis=2)) # suma idzie po wierszach ale szuka minium z kolumn np 9,8,2,4 to 2

[[1 3 1]
 [6 0 0]
 [1 0 0]
 [1 0 1]]


https://www.sharpsightlabs.com/blog/numpy-axes-explained/

In [168]:
M = np.random.randint(10, size=(2, 3, 4))
print(M)

[[[6 7 6 2]
  [9 2 1 2]
  [6 5 5 9]]

 [[5 8 9 6]
  [7 6 7 3]
  [2 2 6 3]]]


In [169]:
print(M.sum(axis=0))
M.min(axis=1)

[[11 15 15  8]
 [16  8  8  5]
 [ 8  7 11 12]]


array([[6, 2, 1, 2],
       [2, 2, 6, 3]])

In [174]:
x = np.array([1, 2, 3, 4, 5])

In [175]:
x < 3

array([ True,  True, False, False, False])

In [176]:
x > 3

array([False, False, False,  True,  True])

In [177]:
x == 3

array([False, False,  True, False, False])

In [178]:
x = np.random.randint(10, size=(4, 4))

In [179]:
x

array([[9, 3, 4, 7],
       [8, 3, 3, 3],
       [5, 9, 2, 6],
       [6, 8, 8, 8]])

In [180]:
np.count_nonzero(x < 6) #ile wartości jest mniejsze od 6

7

In [181]:
np.sum(x < 6, axis = 1) # ile wartości jest mniejsze od 6 ale wiersze ( dla 2ch wymiarów)

array([2, 3, 2, 0])

In [182]:
np.sum(x < 6, axis = 0) #no i kolumnami jedziemy

array([1, 2, 3, 1])

In [185]:
# Czy jest wartość mniejsza niż 0?
np.any(x < 0)

False

In [186]:
x < 5

array([[False,  True,  True, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [187]:
x[x<5] # tam gdzie tru zwróci nam wartości z tego miejsca

array([3, 4, 3, 3, 3, 2])

In [188]:
x = np.random.randint(100, size=10)

In [189]:
x

array([ 4, 44, 97, 92, 16, 27, 62, 35, 39, 64])

In [190]:
ind = [3,7,2] # podajemy indeksy w liscie
x[ind] # poda wartości dla tych indeksów

array([92, 35, 97])

In [191]:
# zrobimy z jednowymiarowej dwuwymiarową tablicę o wartościach z indeksów n
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[92, 35],
       [16, 27]])

In [218]:
x = np.random.randint(100, size=(5, 5))

In [219]:
x

array([[26, 65, 64, 19, 15],
       [92, 72, 72, 59, 54],
       [82, 81, 88, 54, 44],
       [32, 92, 82, 97, 73],
       [62, 64, 92, 10, 45]])

In [220]:
x[2, [0, 1, 2]]

array([82, 81, 88])

In [201]:
x[1:,[2,0,1]]

array([[48, 76, 63],
       [73, 36, 45],
       [55, 66,  5],
       [26, 31,  2]])

In [202]:
np.sort(x) # to sortuje ale nie nadpisuje

array([[12, 14, 16, 48, 74],
       [ 0, 33, 48, 63, 76],
       [36, 45, 50, 60, 73],
       [ 5, 43, 55, 66, 80],
       [ 2, 26, 31, 31, 57]])

In [221]:
x

array([[26, 65, 64, 19, 15],
       [92, 72, 72, 59, 54],
       [82, 81, 88, 54, 44],
       [32, 92, 82, 97, 73],
       [62, 64, 92, 10, 45]])

In [204]:
x.sort() # sortuje i zmienia oryginalną tablice !!!

In [231]:
x

array([[26, 65, 64, 19, 15],
       [92, 72, 72, 59, 54],
       [82, 81, 88, 54, 44],
       [32, 92, 82, 97, 73],
       [62, 64, 92, 10, 45]])

In [222]:
i = np.argsort(x) # zwrca jak indeksy jeśli byśmy posorotowali tabelę, czyli sortuje wartości przez mapowanie

In [229]:
i

array([[4, 3, 0, 2, 1],
       [4, 3, 1, 2, 0],
       [4, 3, 1, 0, 2],
       [0, 4, 2, 1, 3],
       [3, 4, 0, 1, 2]])

In [233]:
x[i]

array([[[62, 64, 92, 10, 45],
        [32, 92, 82, 97, 73],
        [26, 65, 64, 19, 15],
        [82, 81, 88, 54, 44],
        [92, 72, 72, 59, 54]],

       [[62, 64, 92, 10, 45],
        [32, 92, 82, 97, 73],
        [92, 72, 72, 59, 54],
        [82, 81, 88, 54, 44],
        [26, 65, 64, 19, 15]],

       [[62, 64, 92, 10, 45],
        [32, 92, 82, 97, 73],
        [92, 72, 72, 59, 54],
        [26, 65, 64, 19, 15],
        [82, 81, 88, 54, 44]],

       [[26, 65, 64, 19, 15],
        [62, 64, 92, 10, 45],
        [82, 81, 88, 54, 44],
        [92, 72, 72, 59, 54],
        [32, 92, 82, 97, 73]],

       [[32, 92, 82, 97, 73],
        [62, 64, 92, 10, 45],
        [26, 65, 64, 19, 15],
        [92, 72, 72, 59, 54],
        [82, 81, 88, 54, 44]]])

In [212]:
x = np.random.randint(100, size=5)

In [213]:
x

array([88, 81, 65, 19, 65])

In [214]:
i = np.argsort(x)

In [215]:
i

array([3, 2, 4, 1, 0])

In [216]:
x[i]

array([19, 65, 65, 81, 88])